In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
execfile('see.py') # object inspector

In [12]:
# if you change the type stubs you may need to reset the mypy cache
import shutil
shutil.rmtree('.mypy_cache') 

In [25]:
import importlib
importlib.reload(snp)

<module 'snp' from '/Users/brian/Documents/ucsd/bimodal_plotting/sketch-neo-plot/src/snp.py'>

In [26]:
groups = ['control', 'experiment']

durations = [
    [18, 15.42, 25.55, 12.56, 8.67],
    [7.31, 9.66, 13.64, 14.92, 18.47]
] # durations[0] corresponds to the `control` group, durations[1] corresponds to the `experiment` group

success = [
    [1, 1, 0, 0, 1],
    [0, 0, 1, 1, 1]
] # success[0] corresponds to the `control` group, success[1] corresponds to the `experiment` group

time_limit = 30

In [28]:
counts = [4, 0, 3, 6, 10]

In [65]:
def plot_counts(counts, ci_lo, ci_hi):
    fig = plt.figure(layout='tight')
    ax = fig.add_subplot(1, 1, 1, frameon=False)

    bars = ax.bar(np.arange(len(counts)), counts, edgecolor=(0.00, 0.00, 0.00), linewidth=3, bottom=0.72, width=1)
    ax.set_ylim(bottom=0)
    ticks = ax.set_yticks([])
    ticks2 = ax.set_xticks([])
    # polygon = ax.axhspan(1.8, 3.3, xmin=0.09, xmax=0.66)
    # polygon2 = ax.axvspan(1.8, 3.2, ymin=0.024, ymax=0.13, color=(0.00, 0.00, 0.00))
    # line_2d = ax.axhline(xmin=0.28, xmax=0.77)
    line_2d = ax.axvline(x=ci_lo, ymin=-0.1, ymax=0.12, color=(0.00, 0.00, 0.00))
line_2d2 = ax.axvline(x=ci_lo, ymin=-0.1, ymax=0.12, color=(0.00, 0.00, 0.00))

    plt.show()

plot_counts(counts, 2.2, 3.5)

IndentationError: unexpected indent (4051785295.py, line 15)

In [22]:
ax.spines.top

In [23]:
snp.methods_for(ax.spines.top)

([''], 'add_callback', float('inf'), "Add a callback function that will be called whenever one of the `.Artist`'s properties changes."),
([''], 'arc_spine', float('inf'), 'Create and return an arc `Spine`.'),
([''], 'axes', float('inf'), 'An Axes object encapsulates all the elements of an individual (sub-)plot in a figure.'),
([''], 'axis', float('inf'), ''),
([''], 'circular_spine', float('inf'), 'Create and return a circular `Spine`.'),
([''], 'clear', float('inf'), 'Clear the current spine.'),
([''], 'clipbox', float('inf'), ''),
([''], 'contains', float('inf'), 'Test whether the mouse event occurred in the patch.'),
([''], 'contains_point', float('inf'), 'Return whether the given point is inside the patch.'),
([''], 'contains_points', float('inf'), 'Return whether the given points are inside the patch.'),
([''], 'convert_xunits', float('inf'), 'Convert *x* using the unit type of the xaxis.'),
([''], 'convert_yunits', float('inf'), 'Convert *y* using the unit type of the yaxis.'),
(

In [ ]:
last_snp.figure.get_suptitle()
'last_snp.figure.axes[0].get_title()'

In [88]:
import ast

code = 'def f(x): pass'

ast.dump(ast.parse(code))

"Module(body=[FunctionDef(name='f', args=arguments(posonlyargs=[], args=[arg(arg='x')], kwonlyargs=[], kw_defaults=[], defaults=[]), body=[Pass()], decorator_list=[])], type_ignores=[])"

In [76]:
type(3.4).__name__

'float'

In [106]:
%%javascript

var x = `asdfasdf
     asdfasdf`;

console.log(x)

<IPython.core.display.Javascript object>

In [95]:
See("snp_ui.type_graph['builtins'].tree.names['list']")

In [45]:
# '__plottery_mypy_temp.make_fig'
# See('snp_ui.type_tree.defs[13]')

# See('snp_ui.mypy_result.types[snp_ui.type_tree.defs[14]]')

# [node.fullname for node in snp_ui.mypy_result.types.keys()]


# okay so this one has the func local definition names in it, as mypy.nodes.NameExpr with a .fullname attribue, but that .fullname is not fully qualified, it's the local name only
# also doesn't have func vars
# types are the vals of the dict
# See("list(snp_ui.mypy_result.types.keys())")

In [ ]:
__plottery_mypy_temp.make_fig

In [66]:
dir(snp_ui.type_graph['__plottery_mypy_temp'])

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__mypyc_attrs__',
 '__mypyc_defaults_setup',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_patch_indirect_dependencies',
 '_type_checker',
 'abspath',
 'add_ancestors',
 'add_dependency',
 'ancestors',
 'caller_line',
 'caller_state',
 'check_blockers',
 'compute_dependencies',
 'compute_fine_grained_deps',
 'data',
 'dep_line_map',
 'dependencies',
 'dependencies_set',
 'dependency_lines',
 'dependency_priorities',
 'detect_possibly_undefined_vars',
 'early_errors',
 'externally_same',
 'fine_grained_deps_loaded',
 'finish_passes',
 'fix_cross_refs',
 'free_state',
 'generate_ignore_without_code_notes',
 'generate_unused_ignore_notes',
 'id',
 'ignore_all',

In [47]:
snp.notebook_as_code_module_name

'__plottery_mypy_temp'

In [84]:
# plt._get_backend_mod().show

for figure_manager in mpl._pylab_helpers.Gcf.get_all_fig_managers():
    print(figure_manager.canvas.figure)


#     show._to_draw = []
# finally:
#     show._to_draw = []

import matplotlib_inline

matplotlib_inline.backend_inline.show._to_draw


[]

In [160]:
list(paths3._paths[0].vertices)

[array([ 0. , -0.5]),
 array([ 0.13260155, -0.5       ]),
 array([ 0.25978994, -0.44731685]),
 array([ 0.35355339, -0.35355339]),
 array([ 0.44731685, -0.25978994]),
 array([ 0.5       , -0.13260155]),
 array([0.5, 0. ]),
 array([0.5       , 0.13260155]),
 array([0.44731685, 0.25978994]),
 array([0.35355339, 0.35355339]),
 array([0.25978994, 0.44731685]),
 array([0.13260155, 0.5       ]),
 array([0. , 0.5]),
 array([-0.13260155,  0.5       ]),
 array([-0.25978994,  0.44731685]),
 array([-0.35355339,  0.35355339]),
 array([-0.44731685,  0.25978994]),
 array([-0.5       ,  0.13260155]),
 array([-0.5,  0. ]),
 array([-0.5       , -0.13260155]),
 array([-0.44731685, -0.25978994]),
 array([-0.35355339, -0.35355339]),
 array([-0.25978994, -0.44731685]),
 array([-0.13260155, -0.5       ]),
 array([ 0. , -0.5]),
 array([ 0. , -0.5])]

Path(array([[ 0.        , -0.5       ],
       [ 0.13260155, -0.5       ],
       [ 0.25978994, -0.44731685],
       [ 0.35355339, -0.35355339],
       [ 0.44731685, -0.25978994],
       [ 0.5       , -0.13260155],
       [ 0.5       ,  0.        ],
       [ 0.5       ,  0.13260155],
       [ 0.44731685,  0.25978994],
       [ 0.35355339,  0.35355339],
       [ 0.25978994,  0.44731685],
       [ 0.13260155,  0.5       ],
       [ 0.        ,  0.5       ],
       [-0.13260155,  0.5       ],
       [-0.25978994,  0.44731685],
       [-0.35355339,  0.35355339],
       [-0.44731685,  0.25978994],
       [-0.5       ,  0.13260155],
       [-0.5       ,  0.        ],
       [-0.5       , -0.13260155],
       [-0.44731685, -0.25978994],
       [-0.35355339, -0.35355339],
       [-0.25978994, -0.44731685],
       [-0.13260155, -0.5       ],
       [ 0.        , -0.5       ],
       [ 0.        , -0.5       ]]), array([ 1,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        

In [101]:
fig.__class__

matplotlib.figure.Figure

In [100]:
See('ax.legend')

In [24]:
print(plt.figure.__doc__)


    Create a new figure, or activate an existing figure.

    Parameters
    ----------
    num : int or str or `.Figure` or `.SubFigure`, optional
        A unique identifier for the figure.

        If a figure with that identifier already exists, this figure is made
        active and returned. An integer refers to the ``Figure.number``
        attribute, a string refers to the figure label.

        If there is no figure with the identifier or *num* is not given, a new
        figure is created, made active and returned.  If *num* is an int, it
        will be used for the ``Figure.number`` attribute, otherwise, an
        auto-generated integer value is used (starting at 1 and incremented
        for each new figure). If *num* is a string, the figure label and the
        window title is set to this value.  If num is a ``SubFigure``, its
        parent ``Figure`` is activated.

    figsize : (float, float), default: :rc:`figure.figsize`
        Width, height in inches.

    dpi :

In [6]:
colors_t = mypy.types.get_proper_type(snp.type_graph['__temp'].tree.names['colors'].type)
colors_t

builtins.list[builtins.str]

In [7]:
colors_arg_t = mypy.types.get_proper_type(snp.type_graph['matplotlib.axes._axes'].tree.names['Axes'].node.names['bar'].type.arg_types[6])
colors_arg_t

typing.Sequence[Union[builtins.int, builtins.str]]

In [8]:
mypy.subtypes.is_subtype(colors_t, colors_arg_t)

1

In [29]:
mypy.types.get_proper_type(snp.type_graph['__temp'].tree.names['square_wave'].type)

Any

In [6]:
import mypy.api
from mypy import build
from mypy.options import Options
from mypy.nodes import FuncDef
from visitor_mypy import TraverserVisitor

# Example code containing the function we want to analyze
example_code = """
def example_function(a: int, b: str) -> str:
    c = a + 5
    d = b.upper()
    return d
"""

class VariableTypeVisitor(TraverserVisitor):
    def __init__(self, type_map, scope):
        self.type_map = type_map
        self.scope = scope

    def visit_func_def(self, def_node: FuncDef):
        print('hi')
        if def_node.fullname == self.scope:
            for var, typ in self.type_map.items():
                if var.startswith(def_node.fullname):
                    local_name = var.split('.')[-1]
                    print(f"{local_name}: {typ}")

def analyze_code(code: str, scope: str):
    # Parse the code using MyPy
    options = Options()
    options.show_traceback = True
    result = build.build(sources=[build.BuildSource(None, '__main__', code)], options=options)
    if result.errors:
        for error in result.errors:
            print(error)
        return

    # Get the symbol table (type map)
    type_map = result.types

    # Use a visitor to find the function of interest
    visitor = VariableTypeVisitor(type_map, scope)
#     print(result.files.values())
    for file in result.files.values():
        visitor.visit_mypy_file(file)

# Analyze the example code
analyze_code(example_code, 'example_function')